config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  resources :users
  resources :dashboard
  resources :sessions
  resources :articles

  root 'welcome#index'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 5 } #validates that there is a title in the post.
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates_uniqueness_of :email
    validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?

    private
        def user_logged_in!
            return if current_user.present?
            flash[:error] = "Vänligen logga in för att komma åt denna sida"
            redirect_to login_url
        end

        def sign_out
            session[:user_id] = nil
            #reset_session
        end

        def current_user
            #return user if it is already set OR set it to:
            @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
        end

        #med if statement om användaren är inloggad
        def current_user?
            current_user_present?
        end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end

    end

    def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :user_logged_in!

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
        def new
    end

    def create
        user = User.find_by email: params[:email].downcase
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            flash[:notice] = "Välkommen. Du är nu inloggad!"
            redirect_to root_path
        else
            flash.now[:notice] = "Felaktig e-postadress eller lösenord"
            render 'new'
        end
    end

    def destroy
        #hanteras av app_controller
        sign_out
        flash[:notice] = "Du är nu utloggad!"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :user_logged_in!, except: [:index, :show]

    def index
    end

    def new
        @user = User.new
        @users = User.all
    end

    def create
        @users = User.all
        @user = User.new(user_params)

        if @user.save
            flash[:success] = "nya användare tillagd!"
            redirect_to root_url
        else
            render 'new'
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:success] = "adminstratören är borttagen"
        redirect_to '/users/new'
    end

    private

        def user_params
            params.require(:user).permit(:email, :password, :password_confirmation)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr class="articles-list">
      <td><%= article.title %></td>
      <td><%= article.text %></td>

      <td><%= link_to 'Show', article_path(article) %></td>
      <% if current_user %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %> |
<%= link_to 'Edit', edit_article_path(@article) %>

app/views/dashboard/index.html.erb
<h1>This be the dashboard</h1>
<p>It's restricted.</p>

<iframe src="http://giphy.com/embed/vCKC987OpQAco?html5=true" width="480" height="602" frameBorder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usermodel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <div class="user_header">
        <% if current_user %>
            Logged in as: <%= current_user.email %> | <%= link_to 'Admin Dashboard', "/dashboard" %> | <%= link_to 'Sign up', new_user_path %> | <%= link_to 'Log out', logout_path %>
        <% else %>
            <%= link_to 'Log in', new_session_path %>
        <% end %>
    </div>
    <%= yield %>
</div>

</body>
</html>

app/views/users/index.html.erb
hello?

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>